spring.application.name=spring-boot-logging-configuration
server.port=8282


# Logging file path
logging.file.debug.path=logs/debug.log
logging.file.info.path=logs/info.log
logging.file.warn.path=logs/warn.log
logging.file.error.path=logs/error.log
